spring: 
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0 
      
security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:8006/oauth/authorize
      access-token-uri: http://localhost:9006/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8006/oauth/token_key      

zuul:
  add-host-header: true
  retryable: false
#  routes:
#    springCloud-client:
#      path: /springCloud-client/**
#      service-id: springCloud-client
#      sensitive-headers:
#    springCloud-security:
#      path: /springCloud-security/**
#      service-id: springCloud-security
#      sensitive-headers:
#      custom-sensitive-headers: true  
      
        
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
